import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const ListOfSonyTrademarks: NextPage = () => {
  return (
    <>
      <Head>
        <title>List Of Sony Trademarks</title>
      </Head>

      <Container>{TRADEMARKS.join(", ")}.</Container>
    </>
  );
};

export default ListOfSonyTrademarks;

const Container = styled.main`
  background-color: #eee;
  padding: 4rem;
  text-align: justify;
  hyphens: auto;
`;

const TRADEMARKS = [
  "3 MAX+",
  "700 Series",
  "A Vision For Business",
  "a2DVD",
  "ACAMS",
  "Access Center",
  "AccuPower",
  "Accurate Image Restoration",
  "Active Prism",
  "Advanced HAD",
  "Advanced Intelligent Tape",
  "Advanced Storage by Sony",
  "AIBO",
  "Sony α",
  "AIR",
  "Air-Egg",
  "AirTrac",
  "America's Digital Yearbook",
  "APOS",
  "ASC",
  "ATRAC",
  "ATRAC3",
  "Audio Very Important Professional Club",
  "Audio VIP Club",
  "Auto Access",
  "Auto Clock Reveal",
  "Auto Dialer",
  "Auto ImageSet",
  "Auto Shutter",
  "AutoAlert",
  "AutoCenter and Size",
  "Automatic Music Sensor",
  "AV Laser",
  "BabyCall",
  "Backglow",
  "Because There’s So Much More to Hear",
  "Beta Hi-Fi",
  "Beta/Plex",
  "Betacam",
  "Betacam SP",
  "Betacam SX",
  "Betacart",
  "Betamax",
  "Betamovie",
  "BetaScan",
  "BetaScanII",
  "BetaSkipScan",
  "Bicro-Beam",
  "Bidirex",
  "BiERA",
  "Bitcorder",
  "Bloggie",
  "Blue ICS",
  "Blu-ray Disc",
  "BoxEdit",
  "BRAVIA",
  "Brilliant Color and Sound",
  "Cable Mouse",
  "Cappra",
  "Carbonmirror",
  "Carrier Gate",
  "Cassette-corder",
  "CCD Iris",
  "CCD Protection Plan",
  "CD Complete",
  "CD Complete Pro",
  "CD Ease",
  "CD Extreme",
  "CD-Text",
  "CD-IT",
  "CD-IT Pro",
  "CD-ROM",
  "CD-ROM Discman",
  "Cdit",
  "CDit Pro",
  "Cell",
  "Century Media",
  "Cerasin Chassis",
  "Change the Way You Hear the World",
  "Change The Way You Remember The World",
  "Change the Way You See the World",
  "Channel Magic",
  "Childloc",
  "Choose Your Definition",
  "CineAlta",
  "Cinema 8",
  "CineMotion",
  "Cinenet",
  "Cineza",
  "Clear Scan",
  "Clear Scan 25",
  "Clear Voice",
  "ClearScan",
  "ClearScan 25",
  "Click to DVD",
  "CLIÉ",
  "Clip Motion",
  "ClipEdit",
  "Cliplink",
  "ClipMaster",
  "ClipServer",
  "Color Pure Filter",
  "Commercial Pass",
  "Compact Series",
  "Completing the Picture",
  "Conductor",
  "Confer-Corder",
  "Connect & Create",
  "Converting The Industry Bit By Bit",
  "Corporate Audio",
  "CRVdisc",
  "Custom File",
  "Custom Index",
  "Cyber-shot",
  "Cyber-shot Pro",
  "Cyberframe",
  "D-WAVE",
  "D-WAVE Cosm",
  "D-WAVE Zuma",
  "Dash",
  "D8",
  "D8",
  "DASH",
  "Data Discman",
  "Data Media",
  "Datstation",
  "DD230",
  "DDE",
  "DDL",
  "DDS/Digital Data Storage",
  "DDS2/Digital Data Storage",
  "DDS3/Digital Data Storage",
  "DDS4/Digital Data Storage",
  "Defining the Digital Future",
  "Desktop Library",
  "DG5CL",
  "Digital Betacam",
  "Digital Cinema Sound",
  "Digital Dream",
  "Digital Dream Kids",
  "Digital Dynamic Convergence",
  "Digital FlexRes",
  "Digital Gate",
  "Digital Link",
  "Digital Message Shuttle",
  "Digital Monitor Series",
  "Digital Network Recorder",
  "Digital PCLink",
  "Digital Reality Creation",
  "Digital Relay",
  "Digital Signal Transfer",
  "Digital Sketch",
  "Digital Sparkle",
  "Digital Sync",
  "Digital With Soul",
  "Digital. Powerful. Transportable.",
  "Digital8",
  "Direct access",
  "Direct Digital Link",
  "Direct Digital Stream",
  "Direct Stream Digital",
  "Direct Tuning",
  "Disc Explorer",
  "Disc Memo",
  "Disc2Phone",
  "Discam",
  "DiscJockey",
  "Discman",
  "Disk B-Roll",
  "Display Mouse",
  "Displays by Sony",
  "Disturb the Peace",
  "DJ Bank",
  "DME Link",
  "DNAS",
  "Donpisha",
  "DRC",
  "Dream Machine",
  "DreamLink",
  "Drive My Imagination",
  "DSD",
  "DSP Axis",
  "DST",
  "DT",
  "DTF",
  "DTF",
  "dtv-Ready",
  "dtv-Ready",
  "Dual Adjust Head",
  "Dual Axis",
  "Dual Discrete",
  "Dual Room Link Control",
  "DualShock",
  "DVCam",
  "DVD Dream",
  "DVD Navigator",
  "DVD Style",
  "DVgate",
  "DynaFit",
  "Dynalatitude",
  "Dynamic Color",
  "Dynamic Focus",
  "Dynamic Picture",
  "Dynamic Receiver",
  "Dynamic Tracking",
  "Dynamicron",
  "e-conference",
  "E-FILE",
  "Easy Activation",
  "EasySearch",
  "Eco Info",
  "ED Beta",
  "Edit Monitor",
  "Edit Search",
  "EditStation",
  "Elliptical Correction System",
  "eMarker",
  "Enhanced Elliptical Correction System",
  "Ergo-Angle",
  "ESP",
  "ESP MAX",
  "Evaticle",
  "eVilla",
  "Exmor",
  "Express Commander",
  "Express Navigator",
  "Express Support",
  "Express Tuning",
  "Extralloy",
  "Extreme Editing",
  "Exwave HAD",
  "EZ AUDIO",
  "EZ Editor",
  "EZ Flip Commander",
  "EZ Memories",
  "EZ-Flip",
  "Ezfit",
  "EAT SLEEP PLAY",
  "FastPort",
  "FD Trinitron/WEGA",
  "Flash Recording System",
  "Flat Out Better",
  "Flexicart",
  "Flexsys",
  "Flexys",
  "Flying Erase",
  "Fontopia",
  "Forget to Set",
  "Forget-to-Set",
  "Fulfil",
  "Full Color Sound",
  "Fun & Games",
  "FunMail",
  "Fyla",
  "G Chassis",
  "G-Chassis",
  "G-Sense",
  "G-Protection",
  "G-Station",
  "Game Sync",
  "Game Xpand",
  "GeoLock Plus",
  "Get It Backwards",
  "Giga Pocket",
  "GIGAMO",
  "Glasstron",
  "Gold Plug",
  "GoldPlus",
  "Grand Wega",
  "Graphic Picture Enhancement",
  "Great Products Great People",
  "GVIF",
  "H.EAR",
  "Handshake design",
  "Handycam",
  "Handycam Pro",
  "Handycam Vision",
  "HDCAM",
  "HDTV",
  "HDNA",
  "HDVS",
  "HDVS",
  "HF High Fidelity",
  "Hi Band",
  "Hi-Band",
  "Hi-eye Q",
  "Hi-Packing",
  "Hi-Scan",
  "Hi-Scan 1080I",
  "Hi8",
  "Hi8 Editor",
  "HiDensity",
  "High Density Linear",
  "High Density Linear Converter",
  "HMZ-T1",
  "Home Entertainment Universe",
  "Home-Jet",
  "Hyper HAD",
  "Hyper Metal",
  "HZDM",
  "I-Link",
  "i.LINK",
  "ID Telephone",
  "IE / Ion Energy",
  "ImageStation",
  "Indextron",
  "InfoLithium",
  "Infostick",
  "Innovation At Work",
  "Integrated System Commander",
  "Intelligent Dialer",
  "Intellilight",
  "Intellitape",
  "Isara",
  'It\'s A Sony "S"',
  "It's As Easy As A Floppy",
  "Izziton",
  "Jfutura",
  "JJTRON",
  "Jog dial",
  "JumboTron",
  "JumboWall",
  "LanBacker",
  "LANC",
  "LaserLink",
  "Lasermax",
  "Leading The Way",
  "Learn From the Leaders",
  "Legato Linear",
  "Life Just Got Better",
  "Light Sensor",
  "Lightsensor",
  "Lissa",
  "Liv",
  "Live in Your World, Play In Ours",
  "LocationFree[1]",
  "Lumisponder",
  "Macro Storage Through Patented Micro Technology",
  "MacView",
  "Magic Link",
  "MagicGate",
  "Make the Internet Yours",
  "Making Business Pleasure",
  "Marine Pack",
  "Matrix Sound",
  "Matrix Surround",
  "Mavica",
  "Mavicap",
  "Mavicard",
  "Mavigraph",
  "Mavipak",
  "Max-8",
  "Maxxum",
  "Maximum Television",
  "Maximum TV",
  "MD Link",
  "MD Link Plus",
  "MD View",
  "MD Walkman",
  "MD Walkman",
  "MDLP",
  "MDP Muli Disc Player",
  "Media Bar",
  "Media Communicator",
  "Media Forum",
  "Media Mover",
  "Media Park",
  "Media Window",
  "Mega Bass",
  "Mega Bass Port",
  "Mega Storage",
  "Mega Watchman",
  "MegaStorage",
  "Memory Match Ringing",
  "Memory Stick",
  "Memory Stick Micro M2",
  "Memory Stick Pro Duo",
  "Memory Stick Duo",
  "Memory Stick Pro-HG",
  "Menu Disc",
  "MenuNav",
  "Messenger Card",
  "Metal Select",
  "Metreon",
  "MG/MemoryStick",
  "Micro Beam",
  "Micro Vault",
  "Microblack",
  "Microfocus",
  "MICROMV",
  "MID",
  "MiniDisc",
  "Mirrorblack",
  "Missioncontrol",
  "MobilePort",
  "Motion Eye",
  "MovieShaker",
  "MPEG IMX",
  "Multi Channel Access",
  "Multi Disc Player",
  "Multi-Channel Access",
  "Multiscan",
  "Music Clip",
  "Music Pops",
  "Musiclub",
  "Musicruise",
  "My Entertainment, My Place, My Time",
  "My First Sony",
  "My Life Online",
  "Mylo",
  "NanoOs",
  "Nasne[2]",
  "nav-u[3]",
  "Net MD",
  "Network SmartCapture",
  "Network Walkman",
  "Newsbase",
  "NewsCache",
  "NightShot and NightShot 0 Lux",
  "No One Can Duplicate Us",
  "No Sweat Internet",
  "Nothing Escapes Us",
  "OctaStation 2.4",
  "Ohm Page",
  "On Time Support",
  "One Box, One System, One Simple Set-Up, One Unbelievable Experience",
  "OpenMG",
  "OPENR",
  "Orchestra Seat",
  "Our Media Is Your Memory",
  "PacITman",
  "Pan Focus",
  "PanFocus",
  "PC by Sony",
  "PC Cam",
  "PCBacker",
  "Pen Tablet",
  "Personal Technology Experience",
  "Personal-Jet",
  "PetaApp",
  "PetaBack",
  "PetaServe",
  "PetaSite",
  "PhatFree",
  "PhatMan",
  "PhatPig",
  "Photoegg",
  "Pico Player",
  "Picture Paradise",
  "PictureBook",
  "Pictured!",
  "PictureGear",
  "PicturePark",
  "PictureToy",
  "Pit Signal Processing",
  "PJ CALC!",
  "PJ Projects!",
  "Plasmatron",
  "Platinum Plus",
  "PlatinumPlus",
  "Playlist Builder",
  "PlayNow",
  "PlayStation",
  "PlayStation 2",
  "PlayStation BB",
  "PlayStation 3",
  "PlayStation Home",
  "PlayStation Network",
  "PlayStation 4",
  "PlayStation 5",
  "PlayStation Portable",
  "PlayStation Vita",
  "Plug and Present",
  "PocketStation",
  "Polygoneater",
  "Portable Music",
  "Portable Music icon",
  "Portable Music With Style",
  "Power Burn",
  "Power Cinema",
  "Power HAD",
  "Power HAD WS",
  "Power Play",
  "Powerful for Work, Portable for Play",
  "Precision Drive",
  "Pressman",
  "PRO 8",
  "Pro Dat Plus",
  "Pro-Optic",
  "Profeel",
  "Program Palette",
  "Projector Station",
  "ProMavica",
  "ProSound",
  "PSone",
  "PSX",
  "PSYC",
  "Qbric",
  "QIC",
  "Qic",
  "Qic-ER",
  "QRIO",
  "QS 2.4",
  "QSDI",
  "Quadrastation 2.4",
  "Quick Start",
  "Quickset",
  "QuickShare",
  "R2 Reality Regenerator",
  "Rapid Access",
  "Ready-Focus",
  "ReadyCharge",
  "Real-Time Storage Workhorse",
  "Reality Regenerator",
  "RealView",
  "Remote Commander",
  "Repeat Learning System",
  "Rewarding Recording",
  "RITE",
  "Rotary Commander",
  "Ruvi",
  "S-Cache Accelerated",
  "S-Link",
  "S-Master",
  "S-TACT",
  "S2",
  "S2 SPORTS",
  "SA-CD",
  "Scene Shuffle",
  "Scoopman",
  "ScreenBlast",
  "SD",
  "Search Media",
  "SecondOpinion",
  "Seeing is Believing",
  "Select",
  "Selfset",
  "Series 7",
  "Servo Stabilizer",
  "Setup Log",
  "Setup Navi",
  "Shigei",
  "Shoot! Store! Show!",
  "Shot Box",
  "Side Shot",
  "Signal Seeker",
  "SignalSeeker",
  "SiteLink",
  "SIXAXIS",
  "SlimDock",
  "Smart Control",
  "SmartDome",
  "SmartFile",
  "SmartProjector",
  "Smooth Scan",
  "SmoothScan",
  "Snap Shot",
  "SnapJack",
  "SnapShot",
  "Snoozinator",
  "SOBAX",
  "So-net",
  "So The Beat Goes On",
  "SoftwarePlus",
  "Solar Window",
  "Soloist",
  "SonicFlow",
  "SonicStage",
  "SonicStage Mastering Studio",
  "Sony",
  "Sony Pictures",
  "Sony Card",
  "Sony Interactive Entertainment",
  "Sony Data Storage. When the Data Really Matters.",
  "Sony Dynamic Digital Sound",
  "Sony Ericsson",
  "Sony Express",
  "Sony Graphics",
  "Sony Innovators",
  "Sony Mobile",
  "Sony Music",
  "Sony Module Express",
  "Sony Online Entertainment",
  "Sony Plaza",
  "Sony Security Systems",
  "Sony Signatures",
  "Sony Style",
  "Sony Style Connect",
  "Sony Tablet",
  "Sony VAIO Direct",
  "Sony Vision-S",
  "Sony Wonder",
  "Sony-matic",
  "Sound Is Meant To Be Heard, Not Seen",
  "Sound-Sensor",
  "Spec Pro",
  "Special Cleaning Mechanism",
  "SPECL",
  "SpectaPix",
  "SpectaProof",
  "Speed Surf",
  "Speedman",
  "Sport MDR",
  "SportsBand",
  "Sportsfinder",
  "Sportspack",
  "Spressa",
  "SSD",
  "Station Memo",
  "Steady Sound",
  "SteadyShot",
  "SteadySound",
  "Storage by Sony",
  "Storage in a Small Format",
  "Storage Rewards",
  "Storage Solutions for Every Business Landscape",
  "StoreManager",
  "StorSolution",
  "StorStation",
  "Straptenna",
  "Streamphone",
  "Street Style",
  "Study Wave",
  "Style",
  "Style Cube",
  "Super Betamovie",
  "Super Bias",
  "Super Bit Mapping",
  "Super Cleaning Mechanism",
  "Super Coat 2",
  "Super Data",
  "Super Fine Pitch",
  "Super HAD CCD",
  "Super Head Cleaner",
  "Super Hi-Band",
  "Super Performance",
  "SuperBeta",
  "SuperBeta Hi Fi",
  "SuperBeta Hi-Fi",
  "SuperBetamax",
  "SuperBright",
  "Superbrix",
  "SuperLite",
  "Supersite",
  "SuperSlim",
  "SuperSmart",
  "SuperStation",
  "SuperTheater",
  "SupportNet",
  "Swing Search",
  "SwivelScreen",
  "Sxnet",
  "Symphony",
  "Synchro Edit",
  "System G",
  "System Link",
  "SystemAlert",
  "SystemWatch",
  "Tab Marker Indexing System",
  "Tap Tunes",
  "Tape Guide",
  "Tape Your Best Shot",
  "TechPort",
  "Tele Plus",
  "Telepix",
  "The Absolute Best Way to Record Your Music",
  "The Art of the Image",
  "The Big Screen For Small Rooms",
  "The Definition of Definition",
  "The Image Studio",
  "The Image, Pure and Simple",
  "The Leader in Digital Audio",
  "The Leader in Digital Technology",
  "The Leader in Optical Disc",
  "The Mini Remote",
  "The Next Generation of Portable Music Is Coming",
  "The Next Golden Age of Television",
  "The Official Currency of Playtime",
  "The Proof is In the Match",
  "The Repeater",
  "The Sony Card",
  "The Sony Partnership",
  "The Tape With A Brain",
  "The Values That Unite Us",
  "There’s A Story Behind Every Image",
  "Three oval design mark",
  "Thumb Scan",
  "Thumb-cam",
  "Touch Pad Commander",
  "TrackID",
  "TrakCam",
  "Trans Com",
  "Trini-lite",
  "Trinicom",
  "Trinicom",
  "Trinicon",
  "Trinitone",
  "Trinitron",
  "Triple X Program",
  "TruEye",
  "Twin-View",
  "U-ceiver",
  "U-matic",
  "Ultimate Color and Sound",
  "Ultra Personal",
  "UMD",
  "UniCommander",
  "UniDome",
  "UniLink",
  "Unimatch",
  "Unimatic",
  "UniPak",
  "Upgrade Your Image",
  "USB Direct Connect",
  "UVWT",
  "UX Turbo",
  "VAIO",
  "VAIO Compo",
  "VAIO Digital Studio",
  "VAIO Select",
  "VAIO Slimtop",
  "VAIO Smart",
  "VAIO Sphere",
  "VAIO World",
  "Vbox",
  "VCR Mouse",
  "Vdeck",
  "Velocity Modulation",
  "Vialta",
  "Video 8",
  "Video Caddy",
  "Video Hi8",
  "Video Memo",
  "Video Printpack",
  "Video Printpak",
  "Video Walkman",
  "Videograph",
  "Videopress",
  "VideoStore",
  "View Font",
  "View Tools",
  "VisionTouch",
  "VisualFlow",
  "Vivax",
  "Vizaro",
  "w.ear",
  "Walkman",
  "WanBacker",
  "WatchCam",
  "WatchCorder",
  "Watchman",
  "WatchSensor",
  "WAV Link",
  "Wave Hawk",
  "WaveHawk",
  "WebSPF",
  "WEGA",
  "Wfine",
  "What's Next Is Now",
  "Where the Customer Is The One and Only",
  "Where The Music Takes You",
  "wisp.ear",
  "WorkStation",
  "World Band Radio",
  "World Band Receiver",
  "Worry Free",
  "Worry Free Recording",
  "Write ‘n Swipe",
  "X tal Lock",
  "X-tal Lock",
  "XBR",
  "XBR2",
  "XBRITE",
  "XPERIA",
  "Xplōd",
  "Xpri",
  "XWIDE",
  "XrossMediaBar",
  "Your Digital Key To Information",
  "Z505 SuperSlim Pro",
  "Zero Footprint Design",
  "Zero Lux Shot",
  "Zoomeye",
];
